/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sleazyweasel_sparkle_SparkleActivator */

#ifndef _Included_com_sleazyweasel_sparkle_SparkleActivator
#define _Included_com_sleazyweasel_sparkle_SparkleActivator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sleazyweasel_sparkle_SparkleActivator
 * Method:    initSparkle
 * Signature: (Ljava/lang/String;ZI)V
 */
JNIEXPORT void JNICALL Java_com_sleazyweasel_sparkle_SparkleActivator_initSparkle
  (JNIEnv *, jclass, jstring, jboolean, jint);

#ifdef __cplusplus
}
#endif
#endif
